### ISSUE TITLE
当前端内容列表为空时后端无法正确返回

### ISSUE THREAD

**Issue by DarrenDanielDay** [DarrenDanielDay/TimeLine#3]
假设当前端请求初始数据时发生了网络超时，无法获得初始数据。接下来，网络恢复正常，而当用户按下刷新/更多按钮时，后端得到的时间参数为空字符串，无法返回期望结果，表现为增加的内容始终为0个。

**Comment by DavidLuo216** [comment]
改变refresh处理非法时间字符串的方式，当字符串非法时返回空的posts数组

**Comment by DarrenDanielDay** [comment]
refresh和more-posts接收到空字符串时间参数时的逻辑应当和获取初始数据的逻辑一样

**Comment by DarrenDanielDay** [comment]
通过refresh的测试用例，发现空字符串确实无法通过测试。
测试用例代码在[这里](https://github.com/DarrenDanielDay/TimeLine/blob/master/src/test/java/cn/ecnuer996/timeline/controller/UserControllerTest.java#L43)。

**Comment by DarrenDanielDay** [comment]
修复API：refresh存在的问题。原因是使用了
```java
time!=""
```
来判断字符串是否为空。应当使用
```java
!"".equals(time)
```
[修改见此处](https://github.com/DarrenDanielDay/TimeLine/commit/7659dff4583dc6b4f51c5fb2fae31cae9d98c0cc#diff-c11d9b2bb254f6393a7db4cac5f33bceL40)
