### ISSUE TITLE
测试用例testRefreshNormally运行时间过长

### ISSUE THREAD

**Issue by DarrenDanielDay** [DarrenDanielDay/TimeLine#4]
测试用例代码在[这里](https://github.com/DarrenDanielDay/TimeLine/commit/dd4d4f0c7b5d5558b9820eb832c4640d241e575b#diff-90bdb670455cbffd39f45693a2d4ea98R28)。
第一个参数测了11秒，第二个参数测了三分钟还没有结果。

**Comment by DarrenDanielDay** [comment]
已查明原因。
由于没有其他模块，新数据无法自然产生，因此我们考虑了在调用API：refresh的时候产生请求附带的时间参数到当前时间之间的假数据。
而测试用例中有一个非常久远的时间参数（***一年之前***），因此产生了大量的数据，导致运行时间变长。

**Comment by IwAntACqaq** [comment]
现采用mock打桩方法，实现真正的单元测试，脱离数据库等干扰，已经将测试时间大量削减。
至此改问题解决。 
[这里](https://github.com/DarrenDanielDay/TimeLine/commit/8b691b22035a454a6db53f2444fe46b017e83123#diff-90bdb670455cbffd39f45693a2d4ea98L31)
